// This file was auto-generated by Fern from our API Definition.

package generatorexec

import (
	json "encoding/json"
	fmt "fmt"
	core "github.com/fern-api/ir-go/v65/core"
)

type BasicLicense struct {
	Id LicenseId `json:"id,omitempty"`
}

func (b *BasicLicense) String() string {
	if value, err := core.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

type CratesGithubPublishInfo struct {
	RegistryUrl                   string              `json:"registryUrl"`
	PackageName                   string              `json:"packageName"`
	TokenEnvironmentVariable      EnvironmentVariable `json:"tokenEnvironmentVariable"`
	ShouldGeneratePublishWorkflow *bool               `json:"shouldGeneratePublishWorkflow,omitempty"`
}

func (c *CratesGithubPublishInfo) String() string {
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CratesRegistryConfig struct {
	RegistryUrl string `json:"registryUrl"`
	Token       string `json:"token"`
	PackageName string `json:"packageName"`
}

func (c *CratesRegistryConfig) String() string {
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type CustomLicense struct {
	Filename string `json:"filename"`
}

func (c *CustomLicense) String() string {
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

type EnvironmentVariable = string

type GeneratorConfig struct {
	DryRun                 bool                   `json:"dryRun"`
	IrFilepath             string                 `json:"irFilepath"`
	OriginalReadmeFilepath *string                `json:"originalReadmeFilepath,omitempty"`
	License                *LicenseConfig         `json:"license,omitempty"`
	Output                 *GeneratorOutputConfig `json:"output,omitempty"`
	// Deprecated. Use output.mode instead.
	Publish                  *GeneratorPublishConfig `json:"publish,omitempty"`
	WorkspaceName            string                  `json:"workspaceName"`
	Organization             string                  `json:"organization"`
	CustomConfig             interface{}             `json:"customConfig,omitempty"`
	Environment              *GeneratorEnvironment   `json:"environment,omitempty"`
	Whitelabel               bool                    `json:"whitelabel"`
	WriteUnitTests           bool                    `json:"writeUnitTests"`
	GeneratePaginatedClients *bool                   `json:"generatePaginatedClients,omitempty"`
	GenerateOauthClients     bool                    `json:"generateOauthClients"`
}

func (g *GeneratorConfig) String() string {
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GeneratorEnvironment struct {
	Type   string
	Local  interface{}
	Remote *RemoteGeneratorEnvironment
}

func NewGeneratorEnvironmentFromLocal(value interface{}) *GeneratorEnvironment {
	return &GeneratorEnvironment{Type: "local", Local: value}
}

func NewGeneratorEnvironmentFromRemote(value *RemoteGeneratorEnvironment) *GeneratorEnvironment {
	return &GeneratorEnvironment{Type: "remote", Remote: value}
}

func (g *GeneratorEnvironment) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"_type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	g.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "local":
		value := make(map[string]interface{})
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Local = value
	case "remote":
		value := new(RemoteGeneratorEnvironment)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Remote = value
	}
	return nil
}

func (g GeneratorEnvironment) MarshalJSON() ([]byte, error) {
	switch g.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", g.Type, g)
	case "local":
		var marshaler = struct {
			Type  string      `json:"_type"`
			Local interface{} `json:"local,omitempty"`
		}{
			Type:  g.Type,
			Local: g.Local,
		}
		return json.Marshal(marshaler)
	case "remote":
		var marshaler = struct {
			Type string `json:"_type"`
			*RemoteGeneratorEnvironment
		}{
			Type:                       g.Type,
			RemoteGeneratorEnvironment: g.Remote,
		}
		return json.Marshal(marshaler)
	}
}

type GeneratorEnvironmentVisitor interface {
	VisitLocal(interface{}) error
	VisitRemote(*RemoteGeneratorEnvironment) error
}

func (g *GeneratorEnvironment) Accept(visitor GeneratorEnvironmentVisitor) error {
	switch g.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", g.Type, g)
	case "local":
		return visitor.VisitLocal(g.Local)
	case "remote":
		return visitor.VisitRemote(g.Remote)
	}
}

type GeneratorOutputConfig struct {
	Path                    string              `json:"path"`
	SnippetFilepath         *string             `json:"snippetFilepath,omitempty"`
	SnippetTemplateFilepath *string             `json:"snippetTemplateFilepath,omitempty"`
	PublishingMetadata      *PublishingMetadata `json:"publishingMetadata,omitempty"`
	Mode                    *OutputMode         `json:"mode,omitempty"`
}

func (g *GeneratorOutputConfig) String() string {
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GeneratorPublishConfig struct {
	// Deprecated, use publishTargets instead.
	Registries *GeneratorRegistriesConfig `json:"registries,omitempty"`
	// Deprecated, use publishTargets instead.
	RegistriesV2  *GeneratorRegistriesConfigV2 `json:"registriesV2,omitempty"`
	PublishTarget *GeneratorPublishTarget      `json:"publishTarget,omitempty"`
	Version       string                       `json:"version"`
}

func (g *GeneratorPublishConfig) String() string {
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GeneratorPublishTarget struct {
	Type     string
	Maven    *MavenRegistryConfigV2
	Npm      *NpmRegistryConfigV2
	Pypi     *PypiRegistryConfig
	Postman  *PostmanConfig
	Rubygems *RubyGemsRegistryConfig
	Nuget    *NugetRegistryConfig
	Crates   *CratesRegistryConfig
}

func NewGeneratorPublishTargetFromMaven(value *MavenRegistryConfigV2) *GeneratorPublishTarget {
	return &GeneratorPublishTarget{Type: "maven", Maven: value}
}

func NewGeneratorPublishTargetFromNpm(value *NpmRegistryConfigV2) *GeneratorPublishTarget {
	return &GeneratorPublishTarget{Type: "npm", Npm: value}
}

func NewGeneratorPublishTargetFromPypi(value *PypiRegistryConfig) *GeneratorPublishTarget {
	return &GeneratorPublishTarget{Type: "pypi", Pypi: value}
}

func NewGeneratorPublishTargetFromPostman(value *PostmanConfig) *GeneratorPublishTarget {
	return &GeneratorPublishTarget{Type: "postman", Postman: value}
}

func NewGeneratorPublishTargetFromRubygems(value *RubyGemsRegistryConfig) *GeneratorPublishTarget {
	return &GeneratorPublishTarget{Type: "rubygems", Rubygems: value}
}

func NewGeneratorPublishTargetFromNuget(value *NugetRegistryConfig) *GeneratorPublishTarget {
	return &GeneratorPublishTarget{Type: "nuget", Nuget: value}
}

func NewGeneratorPublishTargetFromCrates(value *CratesRegistryConfig) *GeneratorPublishTarget {
	return &GeneratorPublishTarget{Type: "crates", Crates: value}
}

func (g *GeneratorPublishTarget) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	g.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "maven":
		value := new(MavenRegistryConfigV2)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Maven = value
	case "npm":
		value := new(NpmRegistryConfigV2)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Npm = value
	case "pypi":
		value := new(PypiRegistryConfig)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Pypi = value
	case "postman":
		value := new(PostmanConfig)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Postman = value
	case "rubygems":
		value := new(RubyGemsRegistryConfig)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Rubygems = value
	case "nuget":
		value := new(NugetRegistryConfig)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Nuget = value
	case "crates":
		value := new(CratesRegistryConfig)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Crates = value
	}
	return nil
}

func (g GeneratorPublishTarget) MarshalJSON() ([]byte, error) {
	switch g.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", g.Type, g)
	case "maven":
		var marshaler = struct {
			Type string `json:"type"`
			*MavenRegistryConfigV2
		}{
			Type:                  g.Type,
			MavenRegistryConfigV2: g.Maven,
		}
		return json.Marshal(marshaler)
	case "npm":
		var marshaler = struct {
			Type string `json:"type"`
			*NpmRegistryConfigV2
		}{
			Type:                g.Type,
			NpmRegistryConfigV2: g.Npm,
		}
		return json.Marshal(marshaler)
	case "pypi":
		var marshaler = struct {
			Type string `json:"type"`
			*PypiRegistryConfig
		}{
			Type:               g.Type,
			PypiRegistryConfig: g.Pypi,
		}
		return json.Marshal(marshaler)
	case "postman":
		var marshaler = struct {
			Type string `json:"type"`
			*PostmanConfig
		}{
			Type:          g.Type,
			PostmanConfig: g.Postman,
		}
		return json.Marshal(marshaler)
	case "rubygems":
		var marshaler = struct {
			Type string `json:"type"`
			*RubyGemsRegistryConfig
		}{
			Type:                   g.Type,
			RubyGemsRegistryConfig: g.Rubygems,
		}
		return json.Marshal(marshaler)
	case "nuget":
		var marshaler = struct {
			Type string `json:"type"`
			*NugetRegistryConfig
		}{
			Type:                g.Type,
			NugetRegistryConfig: g.Nuget,
		}
		return json.Marshal(marshaler)
	case "crates":
		var marshaler = struct {
			Type string `json:"type"`
			*CratesRegistryConfig
		}{
			Type:                 g.Type,
			CratesRegistryConfig: g.Crates,
		}
		return json.Marshal(marshaler)
	}
}

type GeneratorPublishTargetVisitor interface {
	VisitMaven(*MavenRegistryConfigV2) error
	VisitNpm(*NpmRegistryConfigV2) error
	VisitPypi(*PypiRegistryConfig) error
	VisitPostman(*PostmanConfig) error
	VisitRubygems(*RubyGemsRegistryConfig) error
	VisitNuget(*NugetRegistryConfig) error
	VisitCrates(*CratesRegistryConfig) error
}

func (g *GeneratorPublishTarget) Accept(visitor GeneratorPublishTargetVisitor) error {
	switch g.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", g.Type, g)
	case "maven":
		return visitor.VisitMaven(g.Maven)
	case "npm":
		return visitor.VisitNpm(g.Npm)
	case "pypi":
		return visitor.VisitPypi(g.Pypi)
	case "postman":
		return visitor.VisitPostman(g.Postman)
	case "rubygems":
		return visitor.VisitRubygems(g.Rubygems)
	case "nuget":
		return visitor.VisitNuget(g.Nuget)
	case "crates":
		return visitor.VisitCrates(g.Crates)
	}
}

type GeneratorRegistriesConfig struct {
	Maven *MavenRegistryConfig `json:"maven,omitempty"`
	Npm   *NpmRegistryConfig   `json:"npm,omitempty"`
}

func (g *GeneratorRegistriesConfig) String() string {
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GeneratorRegistriesConfigV2 struct {
	Maven    *MavenRegistryConfigV2  `json:"maven,omitempty"`
	Npm      *NpmRegistryConfigV2    `json:"npm,omitempty"`
	Pypi     *PypiRegistryConfig     `json:"pypi,omitempty"`
	Rubygems *RubyGemsRegistryConfig `json:"rubygems,omitempty"`
	Nuget    *NugetRegistryConfig    `json:"nuget,omitempty"`
	Crates   *CratesRegistryConfig   `json:"crates,omitempty"`
}

func (g *GeneratorRegistriesConfigV2) String() string {
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GithubOutputMode struct {
	Version string `json:"version"`
	// A full repo url (i.e. https://github.com/fern-api/fern)
	RepoUrl string `json:"repoUrl"`
	// The token scoped to installing the repository. If not specified, the generator
	// should NOT attempt to clone the repository.
	InstallationToken *string `json:"installationToken,omitempty"`
	// The branch to use for README cloning. Defaults to the repository's default branch when omitted.
	Branch      *string            `json:"branch,omitempty"`
	PublishInfo *GithubPublishInfo `json:"publishInfo,omitempty"`
}

func (g *GithubOutputMode) String() string {
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type GithubPublishInfo struct {
	Type     string
	Npm      *NpmGithubPublishInfo
	Maven    *MavenGithubPublishInfo
	Postman  *PostmanGithubPublishInfo
	Pypi     *PypiGithubPublishInfo
	Rubygems *RubyGemsGithubPublishInfo
	Nuget    *NugetGithubPublishInfo
	Crates   *CratesGithubPublishInfo
}

func NewGithubPublishInfoFromNpm(value *NpmGithubPublishInfo) *GithubPublishInfo {
	return &GithubPublishInfo{Type: "npm", Npm: value}
}

func NewGithubPublishInfoFromMaven(value *MavenGithubPublishInfo) *GithubPublishInfo {
	return &GithubPublishInfo{Type: "maven", Maven: value}
}

func NewGithubPublishInfoFromPostman(value *PostmanGithubPublishInfo) *GithubPublishInfo {
	return &GithubPublishInfo{Type: "postman", Postman: value}
}

func NewGithubPublishInfoFromPypi(value *PypiGithubPublishInfo) *GithubPublishInfo {
	return &GithubPublishInfo{Type: "pypi", Pypi: value}
}

func NewGithubPublishInfoFromRubygems(value *RubyGemsGithubPublishInfo) *GithubPublishInfo {
	return &GithubPublishInfo{Type: "rubygems", Rubygems: value}
}

func NewGithubPublishInfoFromNuget(value *NugetGithubPublishInfo) *GithubPublishInfo {
	return &GithubPublishInfo{Type: "nuget", Nuget: value}
}

func NewGithubPublishInfoFromCrates(value *CratesGithubPublishInfo) *GithubPublishInfo {
	return &GithubPublishInfo{Type: "crates", Crates: value}
}

func (g *GithubPublishInfo) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	g.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "npm":
		value := new(NpmGithubPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Npm = value
	case "maven":
		value := new(MavenGithubPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Maven = value
	case "postman":
		value := new(PostmanGithubPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Postman = value
	case "pypi":
		value := new(PypiGithubPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Pypi = value
	case "rubygems":
		value := new(RubyGemsGithubPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Rubygems = value
	case "nuget":
		value := new(NugetGithubPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Nuget = value
	case "crates":
		value := new(CratesGithubPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Crates = value
	}
	return nil
}

func (g GithubPublishInfo) MarshalJSON() ([]byte, error) {
	switch g.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", g.Type, g)
	case "npm":
		var marshaler = struct {
			Type string `json:"type"`
			*NpmGithubPublishInfo
		}{
			Type:                 g.Type,
			NpmGithubPublishInfo: g.Npm,
		}
		return json.Marshal(marshaler)
	case "maven":
		var marshaler = struct {
			Type string `json:"type"`
			*MavenGithubPublishInfo
		}{
			Type:                   g.Type,
			MavenGithubPublishInfo: g.Maven,
		}
		return json.Marshal(marshaler)
	case "postman":
		var marshaler = struct {
			Type string `json:"type"`
			*PostmanGithubPublishInfo
		}{
			Type:                     g.Type,
			PostmanGithubPublishInfo: g.Postman,
		}
		return json.Marshal(marshaler)
	case "pypi":
		var marshaler = struct {
			Type string `json:"type"`
			*PypiGithubPublishInfo
		}{
			Type:                  g.Type,
			PypiGithubPublishInfo: g.Pypi,
		}
		return json.Marshal(marshaler)
	case "rubygems":
		var marshaler = struct {
			Type string `json:"type"`
			*RubyGemsGithubPublishInfo
		}{
			Type:                      g.Type,
			RubyGemsGithubPublishInfo: g.Rubygems,
		}
		return json.Marshal(marshaler)
	case "nuget":
		var marshaler = struct {
			Type string `json:"type"`
			*NugetGithubPublishInfo
		}{
			Type:                   g.Type,
			NugetGithubPublishInfo: g.Nuget,
		}
		return json.Marshal(marshaler)
	case "crates":
		var marshaler = struct {
			Type string `json:"type"`
			*CratesGithubPublishInfo
		}{
			Type:                    g.Type,
			CratesGithubPublishInfo: g.Crates,
		}
		return json.Marshal(marshaler)
	}
}

type GithubPublishInfoVisitor interface {
	VisitNpm(*NpmGithubPublishInfo) error
	VisitMaven(*MavenGithubPublishInfo) error
	VisitPostman(*PostmanGithubPublishInfo) error
	VisitPypi(*PypiGithubPublishInfo) error
	VisitRubygems(*RubyGemsGithubPublishInfo) error
	VisitNuget(*NugetGithubPublishInfo) error
	VisitCrates(*CratesGithubPublishInfo) error
}

func (g *GithubPublishInfo) Accept(visitor GithubPublishInfoVisitor) error {
	switch g.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", g.Type, g)
	case "npm":
		return visitor.VisitNpm(g.Npm)
	case "maven":
		return visitor.VisitMaven(g.Maven)
	case "postman":
		return visitor.VisitPostman(g.Postman)
	case "pypi":
		return visitor.VisitPypi(g.Pypi)
	case "rubygems":
		return visitor.VisitRubygems(g.Rubygems)
	case "nuget":
		return visitor.VisitNuget(g.Nuget)
	case "crates":
		return visitor.VisitCrates(g.Crates)
	}
}

type LicenseConfig struct {
	Type   string
	Basic  *BasicLicense
	Custom *CustomLicense
}

func NewLicenseConfigFromBasic(value *BasicLicense) *LicenseConfig {
	return &LicenseConfig{Type: "basic", Basic: value}
}

func NewLicenseConfigFromCustom(value *CustomLicense) *LicenseConfig {
	return &LicenseConfig{Type: "custom", Custom: value}
}

func (l *LicenseConfig) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	l.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "basic":
		value := new(BasicLicense)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		l.Basic = value
	case "custom":
		value := new(CustomLicense)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		l.Custom = value
	}
	return nil
}

func (l LicenseConfig) MarshalJSON() ([]byte, error) {
	switch l.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", l.Type, l)
	case "basic":
		var marshaler = struct {
			Type string `json:"type"`
			*BasicLicense
		}{
			Type:         l.Type,
			BasicLicense: l.Basic,
		}
		return json.Marshal(marshaler)
	case "custom":
		var marshaler = struct {
			Type string `json:"type"`
			*CustomLicense
		}{
			Type:          l.Type,
			CustomLicense: l.Custom,
		}
		return json.Marshal(marshaler)
	}
}

type LicenseConfigVisitor interface {
	VisitBasic(*BasicLicense) error
	VisitCustom(*CustomLicense) error
}

func (l *LicenseConfig) Accept(visitor LicenseConfigVisitor) error {
	switch l.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", l.Type, l)
	case "basic":
		return visitor.VisitBasic(l.Basic)
	case "custom":
		return visitor.VisitCustom(l.Custom)
	}
}

type LicenseId string

const (
	LicenseIdMit     LicenseId = "MIT"
	LicenseIdApache2 LicenseId = "Apache-2.0"
)

func NewLicenseIdFromString(s string) (LicenseId, error) {
	switch s {
	case "MIT":
		return LicenseIdMit, nil
	case "Apache-2.0":
		return LicenseIdApache2, nil
	}
	var t LicenseId
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (l LicenseId) Ptr() *LicenseId {
	return &l
}

type MavenCentralSignature struct {
	KeyId     string `json:"keyId"`
	Password  string `json:"password"`
	SecretKey string `json:"secretKey"`
}

func (m *MavenCentralSignature) String() string {
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MavenCentralSignatureGithubInfo struct {
	KeyIdEnvironmentVariable     EnvironmentVariable `json:"keyIdEnvironmentVariable"`
	PasswordEnvironmentVariable  EnvironmentVariable `json:"passwordEnvironmentVariable"`
	SecretKeyEnvironmentVariable EnvironmentVariable `json:"secretKeyEnvironmentVariable"`
}

func (m *MavenCentralSignatureGithubInfo) String() string {
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MavenGithubPublishInfo struct {
	RegistryUrl                   string                           `json:"registryUrl"`
	Coordinate                    string                           `json:"coordinate"`
	UsernameEnvironmentVariable   EnvironmentVariable              `json:"usernameEnvironmentVariable"`
	PasswordEnvironmentVariable   EnvironmentVariable              `json:"passwordEnvironmentVariable"`
	Signature                     *MavenCentralSignatureGithubInfo `json:"signature,omitempty"`
	ShouldGeneratePublishWorkflow *bool                            `json:"shouldGeneratePublishWorkflow,omitempty"`
}

func (m *MavenGithubPublishInfo) String() string {
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MavenRegistryConfig struct {
	RegistryUrl string                 `json:"registryUrl"`
	Username    string                 `json:"username"`
	Password    string                 `json:"password"`
	Group       string                 `json:"group"`
	Signature   *MavenCentralSignature `json:"signature,omitempty"`
}

func (m *MavenRegistryConfig) String() string {
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MavenRegistryConfigV2 struct {
	RegistryUrl string                 `json:"registryUrl"`
	Username    string                 `json:"username"`
	Password    string                 `json:"password"`
	Coordinate  string                 `json:"coordinate"`
	Signature   *MavenCentralSignature `json:"signature,omitempty"`
}

func (m *MavenRegistryConfigV2) String() string {
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type NpmGithubPublishInfo struct {
	RegistryUrl                   string              `json:"registryUrl"`
	PackageName                   string              `json:"packageName"`
	TokenEnvironmentVariable      EnvironmentVariable `json:"tokenEnvironmentVariable"`
	ShouldGeneratePublishWorkflow *bool               `json:"shouldGeneratePublishWorkflow,omitempty"`
}

func (n *NpmGithubPublishInfo) String() string {
	if value, err := core.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

type NpmRegistryConfig struct {
	RegistryUrl string `json:"registryUrl"`
	Token       string `json:"token"`
	Scope       string `json:"scope"`
}

func (n *NpmRegistryConfig) String() string {
	if value, err := core.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

type NpmRegistryConfigV2 struct {
	RegistryUrl string `json:"registryUrl"`
	Token       string `json:"token"`
	PackageName string `json:"packageName"`
}

func (n *NpmRegistryConfigV2) String() string {
	if value, err := core.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

type NugetGithubPublishInfo struct {
	RegistryUrl                   string              `json:"registryUrl"`
	PackageName                   string              `json:"packageName"`
	ApiKeyEnvironmentVariable     EnvironmentVariable `json:"apiKeyEnvironmentVariable"`
	ShouldGeneratePublishWorkflow *bool               `json:"shouldGeneratePublishWorkflow,omitempty"`
}

func (n *NugetGithubPublishInfo) String() string {
	if value, err := core.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

type NugetRegistryConfig struct {
	RegistryUrl string `json:"registryUrl"`
	ApiKey      string `json:"apiKey"`
	PackageName string `json:"packageName"`
}

func (n *NugetRegistryConfig) String() string {
	if value, err := core.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

type OutputMetadata struct {
	Description *string                 `json:"description,omitempty"`
	Authors     []*OutputMetadataAuthor `json:"authors,omitempty"`
}

func (o *OutputMetadata) String() string {
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OutputMetadataAuthor struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (o *OutputMetadataAuthor) String() string {
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OutputMode struct {
	Type          string
	Publish       *GeneratorPublishConfig
	DownloadFiles interface{}
	Github        *GithubOutputMode
}

func NewOutputModeFromPublish(value *GeneratorPublishConfig) *OutputMode {
	return &OutputMode{Type: "publish", Publish: value}
}

func NewOutputModeFromDownloadFiles(value interface{}) *OutputMode {
	return &OutputMode{Type: "downloadFiles", DownloadFiles: value}
}

func NewOutputModeFromGithub(value *GithubOutputMode) *OutputMode {
	return &OutputMode{Type: "github", Github: value}
}

func (o *OutputMode) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	o.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "publish":
		value := new(GeneratorPublishConfig)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		o.Publish = value
	case "downloadFiles":
		value := make(map[string]interface{})
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		o.DownloadFiles = value
	case "github":
		value := new(GithubOutputMode)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		o.Github = value
	}
	return nil
}

func (o OutputMode) MarshalJSON() ([]byte, error) {
	switch o.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", o.Type, o)
	case "publish":
		var marshaler = struct {
			Type string `json:"type"`
			*GeneratorPublishConfig
		}{
			Type:                   o.Type,
			GeneratorPublishConfig: o.Publish,
		}
		return json.Marshal(marshaler)
	case "downloadFiles":
		var marshaler = struct {
			Type          string      `json:"type"`
			DownloadFiles interface{} `json:"downloadFiles,omitempty"`
		}{
			Type:          o.Type,
			DownloadFiles: o.DownloadFiles,
		}
		return json.Marshal(marshaler)
	case "github":
		var marshaler = struct {
			Type string `json:"type"`
			*GithubOutputMode
		}{
			Type:             o.Type,
			GithubOutputMode: o.Github,
		}
		return json.Marshal(marshaler)
	}
}

type OutputModeVisitor interface {
	VisitPublish(*GeneratorPublishConfig) error
	VisitDownloadFiles(interface{}) error
	VisitGithub(*GithubOutputMode) error
}

func (o *OutputMode) Accept(visitor OutputModeVisitor) error {
	switch o.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", o.Type, o)
	case "publish":
		return visitor.VisitPublish(o.Publish)
	case "downloadFiles":
		return visitor.VisitDownloadFiles(o.DownloadFiles)
	case "github":
		return visitor.VisitGithub(o.Github)
	}
}

type PostmanConfig struct {
	ApiKey      string `json:"apiKey"`
	WorkspaceId string `json:"workspaceId"`
}

func (p *PostmanConfig) String() string {
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PostmanGithubPublishInfo struct {
	ApiKeyEnvironmentVariable      EnvironmentVariable `json:"apiKeyEnvironmentVariable"`
	WorkspaceIdEnvironmentVariable EnvironmentVariable `json:"workspaceIdEnvironmentVariable"`
}

func (p *PostmanGithubPublishInfo) String() string {
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

// This should effectively be deprecated in favor of a more specific configuration per-output mode (pypi, maven, etc.).
type PublishingMetadata struct {
	PackageDescription *string `json:"package_description,omitempty"`
	PublisherEmail     *string `json:"publisher_email,omitempty"`
	ReferenceUrl       *string `json:"reference_url,omitempty"`
	PublisherName      *string `json:"publisher_name,omitempty"`
}

func (p *PublishingMetadata) String() string {
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PypiGithubPublishInfo struct {
	RegistryUrl                   string              `json:"registryUrl"`
	PackageName                   string              `json:"packageName"`
	UsernameEnvironmentVariable   EnvironmentVariable `json:"usernameEnvironmentVariable"`
	PasswordEnvironmentVariable   EnvironmentVariable `json:"passwordEnvironmentVariable"`
	PypiMetadata                  *PypiMetadata       `json:"pypiMetadata,omitempty"`
	ShouldGeneratePublishWorkflow *bool               `json:"shouldGeneratePublishWorkflow,omitempty"`
}

func (p *PypiGithubPublishInfo) String() string {
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PypiMetadata struct {
	Description       *string                 `json:"description,omitempty"`
	Authors           []*OutputMetadataAuthor `json:"authors,omitempty"`
	Keywords          []string                `json:"keywords,omitempty"`
	DocumentationLink *string                 `json:"documentationLink,omitempty"`
	HomepageLink      *string                 `json:"homepageLink,omitempty"`
}

func (p *PypiMetadata) String() string {
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type PypiRegistryConfig struct {
	RegistryUrl  string        `json:"registryUrl"`
	Username     string        `json:"username"`
	Password     string        `json:"password"`
	PackageName  string        `json:"packageName"`
	PypiMetadata *PypiMetadata `json:"pypiMetadata,omitempty"`
}

func (p *PypiRegistryConfig) String() string {
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type RemoteGeneratorEnvironment struct {
	CoordinatorUrl   string `json:"coordinatorUrl"`
	CoordinatorUrlV2 string `json:"coordinatorUrlV2"`
	Id               string `json:"id"`
}

func (r *RemoteGeneratorEnvironment) String() string {
	if value, err := core.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RubyGemsGithubPublishInfo struct {
	RegistryUrl                   string              `json:"registryUrl"`
	PackageName                   string              `json:"packageName"`
	ApiKeyEnvironmentVariable     EnvironmentVariable `json:"apiKeyEnvironmentVariable"`
	ShouldGeneratePublishWorkflow *bool               `json:"shouldGeneratePublishWorkflow,omitempty"`
}

func (r *RubyGemsGithubPublishInfo) String() string {
	if value, err := core.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type RubyGemsRegistryConfig struct {
	RegistryUrl string `json:"registryUrl"`
	ApiKey      string `json:"apiKey"`
	PackageName string `json:"packageName"`
}

func (r *RubyGemsRegistryConfig) String() string {
	if value, err := core.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
