// This file was auto-generated by Fern from our API Definition.

package dynamic

import (
	fmt "fmt"
	core "github.com/fern-api/ir-go/v63/core"
)

// The user-facing response type containing the generated snippet.
//
// If there are any errors, the snippet will still sometimes represent a
// partial and/or valid result. This is useful for rendering a snippet alongside
// error messages the user can use to diagnose and resolve the problem.
type EndpointSnippetResponse struct {
	Snippet string   `json:"snippet"`
	Errors  []*Error `json:"errors,omitempty"`
}

func (e *EndpointSnippetResponse) String() string {
	if value, err := core.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type Error struct {
	Severity ErrorSeverity `json:"severity,omitempty"`
	Message  string        `json:"message"`
}

func (e *Error) String() string {
	if value, err := core.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type ErrorSeverity string

const (
	ErrorSeverityCritical ErrorSeverity = "CRITICAL"
	ErrorSeverityWarning  ErrorSeverity = "WARNING"
)

func NewErrorSeverityFromString(s string) (ErrorSeverity, error) {
	switch s {
	case "CRITICAL":
		return ErrorSeverityCritical, nil
	case "WARNING":
		return ErrorSeverityWarning, nil
	}
	var t ErrorSeverity
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (e ErrorSeverity) Ptr() *ErrorSeverity {
	return &e
}
