// This file was auto-generated by Fern from our API Definition.

package dynamic

import (
	json "encoding/json"
	fmt "fmt"
	common "github.com/fern-api/ir-go/v63/common"
	core "github.com/fern-api/ir-go/v63/core"
)

type Auth struct {
	Type     string
	Basic    *BasicAuth
	Bearer   *BearerAuth
	Header   *HeaderAuth
	Oauth    *OAuth
	Inferred *InferredAuth
}

func NewAuthFromBasic(value *BasicAuth) *Auth {
	return &Auth{Type: "basic", Basic: value}
}

func NewAuthFromBearer(value *BearerAuth) *Auth {
	return &Auth{Type: "bearer", Bearer: value}
}

func NewAuthFromHeader(value *HeaderAuth) *Auth {
	return &Auth{Type: "header", Header: value}
}

func NewAuthFromOauth(value *OAuth) *Auth {
	return &Auth{Type: "oauth", Oauth: value}
}

func NewAuthFromInferred(value *InferredAuth) *Auth {
	return &Auth{Type: "inferred", Inferred: value}
}

func (a *Auth) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	a.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "basic":
		value := new(BasicAuth)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.Basic = value
	case "bearer":
		value := new(BearerAuth)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.Bearer = value
	case "header":
		value := new(HeaderAuth)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.Header = value
	case "oauth":
		value := new(OAuth)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.Oauth = value
	case "inferred":
		value := new(InferredAuth)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.Inferred = value
	}
	return nil
}

func (a Auth) MarshalJSON() ([]byte, error) {
	switch a.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", a.Type, a)
	case "basic":
		var marshaler = struct {
			Type string `json:"type"`
			*BasicAuth
		}{
			Type:      a.Type,
			BasicAuth: a.Basic,
		}
		return json.Marshal(marshaler)
	case "bearer":
		var marshaler = struct {
			Type string `json:"type"`
			*BearerAuth
		}{
			Type:       a.Type,
			BearerAuth: a.Bearer,
		}
		return json.Marshal(marshaler)
	case "header":
		var marshaler = struct {
			Type string `json:"type"`
			*HeaderAuth
		}{
			Type:       a.Type,
			HeaderAuth: a.Header,
		}
		return json.Marshal(marshaler)
	case "oauth":
		var marshaler = struct {
			Type string `json:"type"`
			*OAuth
		}{
			Type:  a.Type,
			OAuth: a.Oauth,
		}
		return json.Marshal(marshaler)
	case "inferred":
		var marshaler = struct {
			Type string `json:"type"`
			*InferredAuth
		}{
			Type:         a.Type,
			InferredAuth: a.Inferred,
		}
		return json.Marshal(marshaler)
	}
}

type AuthVisitor interface {
	VisitBasic(*BasicAuth) error
	VisitBearer(*BearerAuth) error
	VisitHeader(*HeaderAuth) error
	VisitOauth(*OAuth) error
	VisitInferred(*InferredAuth) error
}

func (a *Auth) Accept(visitor AuthVisitor) error {
	switch a.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", a.Type, a)
	case "basic":
		return visitor.VisitBasic(a.Basic)
	case "bearer":
		return visitor.VisitBearer(a.Bearer)
	case "header":
		return visitor.VisitHeader(a.Header)
	case "oauth":
		return visitor.VisitOauth(a.Oauth)
	case "inferred":
		return visitor.VisitInferred(a.Inferred)
	}
}

type AuthValues struct {
	Type     string
	Basic    *BasicAuthValues
	Bearer   *BearerAuthValues
	Header   *HeaderAuthValues
	Oauth    *OAuthValues
	Inferred *InferredAuthValues
}

func NewAuthValuesFromBasic(value *BasicAuthValues) *AuthValues {
	return &AuthValues{Type: "basic", Basic: value}
}

func NewAuthValuesFromBearer(value *BearerAuthValues) *AuthValues {
	return &AuthValues{Type: "bearer", Bearer: value}
}

func NewAuthValuesFromHeader(value *HeaderAuthValues) *AuthValues {
	return &AuthValues{Type: "header", Header: value}
}

func NewAuthValuesFromOauth(value *OAuthValues) *AuthValues {
	return &AuthValues{Type: "oauth", Oauth: value}
}

func NewAuthValuesFromInferred(value *InferredAuthValues) *AuthValues {
	return &AuthValues{Type: "inferred", Inferred: value}
}

func (a *AuthValues) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	a.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "basic":
		value := new(BasicAuthValues)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.Basic = value
	case "bearer":
		value := new(BearerAuthValues)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.Bearer = value
	case "header":
		value := new(HeaderAuthValues)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.Header = value
	case "oauth":
		value := new(OAuthValues)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.Oauth = value
	case "inferred":
		value := new(InferredAuthValues)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		a.Inferred = value
	}
	return nil
}

func (a AuthValues) MarshalJSON() ([]byte, error) {
	switch a.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", a.Type, a)
	case "basic":
		var marshaler = struct {
			Type string `json:"type"`
			*BasicAuthValues
		}{
			Type:            a.Type,
			BasicAuthValues: a.Basic,
		}
		return json.Marshal(marshaler)
	case "bearer":
		var marshaler = struct {
			Type string `json:"type"`
			*BearerAuthValues
		}{
			Type:             a.Type,
			BearerAuthValues: a.Bearer,
		}
		return json.Marshal(marshaler)
	case "header":
		var marshaler = struct {
			Type string `json:"type"`
			*HeaderAuthValues
		}{
			Type:             a.Type,
			HeaderAuthValues: a.Header,
		}
		return json.Marshal(marshaler)
	case "oauth":
		var marshaler = struct {
			Type string `json:"type"`
			*OAuthValues
		}{
			Type:        a.Type,
			OAuthValues: a.Oauth,
		}
		return json.Marshal(marshaler)
	case "inferred":
		var marshaler = struct {
			Type string `json:"type"`
			*InferredAuthValues
		}{
			Type:               a.Type,
			InferredAuthValues: a.Inferred,
		}
		return json.Marshal(marshaler)
	}
}

type AuthValuesVisitor interface {
	VisitBasic(*BasicAuthValues) error
	VisitBearer(*BearerAuthValues) error
	VisitHeader(*HeaderAuthValues) error
	VisitOauth(*OAuthValues) error
	VisitInferred(*InferredAuthValues) error
}

func (a *AuthValues) Accept(visitor AuthValuesVisitor) error {
	switch a.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", a.Type, a)
	case "basic":
		return visitor.VisitBasic(a.Basic)
	case "bearer":
		return visitor.VisitBearer(a.Bearer)
	case "header":
		return visitor.VisitHeader(a.Header)
	case "oauth":
		return visitor.VisitOauth(a.Oauth)
	case "inferred":
		return visitor.VisitInferred(a.Inferred)
	}
}

type BasicAuth struct {
	Username *Name `json:"username,omitempty"`
	Password *Name `json:"password,omitempty"`
}

func (b *BasicAuth) String() string {
	if value, err := core.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

type BasicAuthValues struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (b *BasicAuthValues) String() string {
	if value, err := core.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

type BearerAuth struct {
	Token *Name `json:"token,omitempty"`
}

func (b *BearerAuth) String() string {
	if value, err := core.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

type BearerAuthValues struct {
	Token string `json:"token"`
}

func (b *BearerAuthValues) String() string {
	if value, err := core.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

type HeaderAuth struct {
	Header *NamedParameter `json:"header,omitempty"`
}

func (h *HeaderAuth) String() string {
	if value, err := core.StringifyJSON(h); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", h)
}

type HeaderAuthValues struct {
	Value interface{} `json:"value,omitempty"`
}

func (h *HeaderAuthValues) String() string {
	if value, err := core.StringifyJSON(h); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", h)
}

// Inferred auth retrieves tokens dynamically. The client constructor parameters
// are defined by the parameters list.
type InferredAuth struct {
	// List of parameters (from token endpoint) needed for auth, including their types.
	Parameters []*NamedParameter `json:"parameters,omitempty"`
}

func (i *InferredAuth) String() string {
	if value, err := core.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

// Parameter values for inferred auth in code snippets.
// The keys are wire values matching the parameters in InferredAuth.
type InferredAuthValues struct {
	// Map of wire values to their example values for snippets.
	Values map[string]interface{} `json:"values,omitempty"`
}

func (i *InferredAuthValues) String() string {
	if value, err := core.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type OAuth struct {
	ClientId     *Name `json:"clientId,omitempty"`
	ClientSecret *Name `json:"clientSecret,omitempty"`
}

func (o *OAuth) String() string {
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type OAuthValues struct {
	ClientId     string `json:"clientId"`
	ClientSecret string `json:"clientSecret"`
}

func (o *OAuthValues) String() string {
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type EndpointId = string

type FernFilepath struct {
	AllParts    []*Name `json:"allParts,omitempty"`
	PackagePath []*Name `json:"packagePath,omitempty"`
	File        *Name   `json:"file,omitempty"`
}

func (f *FernFilepath) String() string {
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

type Name struct {
	OriginalName       string               `json:"originalName"`
	CamelCase          *SafeAndUnsafeString `json:"camelCase,omitempty"`
	PascalCase         *SafeAndUnsafeString `json:"pascalCase,omitempty"`
	SnakeCase          *SafeAndUnsafeString `json:"snakeCase,omitempty"`
	ScreamingSnakeCase *SafeAndUnsafeString `json:"screamingSnakeCase,omitempty"`
}

func (n *Name) String() string {
	if value, err := core.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

type NameAndWireValue struct {
	WireValue string `json:"wireValue"`
	Name      *Name  `json:"name,omitempty"`
}

func (n *NameAndWireValue) String() string {
	if value, err := core.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

type SafeAndUnsafeString struct {
	// this name might overlap with reserved keywords of the language being generated
	UnsafeName string `json:"unsafeName"`
	// this name will NOT overlap with reserved keywords of the language being generated
	SafeName string `json:"safeName"`
}

func (s *SafeAndUnsafeString) String() string {
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type TypeId = string

type WithDocs struct {
	Docs *string `json:"docs,omitempty"`
}

func (w *WithDocs) String() string {
	if value, err := core.StringifyJSON(w); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", w)
}

type Declaration struct {
	FernFilepath *FernFilepath `json:"fernFilepath,omitempty"`
	Name         *Name         `json:"name,omitempty"`
}

func (d *Declaration) String() string {
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type BodyRequest struct {
	PathParameters []*NamedParameter          `json:"pathParameters,omitempty"`
	Body           *ReferencedRequestBodyType `json:"body,omitempty"`
}

func (b *BodyRequest) String() string {
	if value, err := core.StringifyJSON(b); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", b)
}

type Endpoint struct {
	Auth        *Auth              `json:"auth,omitempty"`
	Declaration *Declaration       `json:"declaration,omitempty"`
	Location    *EndpointLocation  `json:"location,omitempty"`
	Request     *Request           `json:"request,omitempty"`
	Response    *Response          `json:"response,omitempty"`
	Examples    []*EndpointExample `json:"examples,omitempty"`
}

func (e *Endpoint) String() string {
	if value, err := core.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type EndpointExample struct {
	Endpoint        *EndpointLocation  `json:"endpoint,omitempty"`
	BaseUrl         *string            `json:"baseURL,omitempty"`
	Environment     *EnvironmentValues `json:"environment,omitempty"`
	Auth            *AuthValues        `json:"auth,omitempty"`
	PathParameters  *Values            `json:"pathParameters,omitempty"`
	QueryParameters *Values            `json:"queryParameters,omitempty"`
	Headers         *Values            `json:"headers,omitempty"`
	RequestBody     interface{}        `json:"requestBody,omitempty"`
	// The unique identifier for the example.
	Id string `json:"id"`
	// The name of the example, if any.
	Name *string `json:"name,omitempty"`
}

func (e *EndpointExample) String() string {
	if value, err := core.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// Represents the endpoint location (e.g. "POST /users").
type EndpointLocation struct {
	Method HttpMethod `json:"method,omitempty"`
	Path   string     `json:"path"`
}

func (e *EndpointLocation) String() string {
	if value, err := core.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type FileUploadRequestBody struct {
	Properties []*FileUploadRequestBodyProperty `json:"properties,omitempty"`
}

func (f *FileUploadRequestBody) String() string {
	if value, err := core.StringifyJSON(f); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", f)
}

type FileUploadRequestBodyProperty struct {
	Type         string
	File         *NameAndWireValue
	FileArray    *NameAndWireValue
	BodyProperty *NamedParameter
}

func NewFileUploadRequestBodyPropertyFromFile(value *NameAndWireValue) *FileUploadRequestBodyProperty {
	return &FileUploadRequestBodyProperty{Type: "file", File: value}
}

func NewFileUploadRequestBodyPropertyFromFileArray(value *NameAndWireValue) *FileUploadRequestBodyProperty {
	return &FileUploadRequestBodyProperty{Type: "fileArray", FileArray: value}
}

func NewFileUploadRequestBodyPropertyFromBodyProperty(value *NamedParameter) *FileUploadRequestBodyProperty {
	return &FileUploadRequestBodyProperty{Type: "bodyProperty", BodyProperty: value}
}

func (f *FileUploadRequestBodyProperty) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	f.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "file":
		value := new(NameAndWireValue)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.File = value
	case "fileArray":
		value := new(NameAndWireValue)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.FileArray = value
	case "bodyProperty":
		value := new(NamedParameter)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		f.BodyProperty = value
	}
	return nil
}

func (f FileUploadRequestBodyProperty) MarshalJSON() ([]byte, error) {
	switch f.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", f.Type, f)
	case "file":
		var marshaler = struct {
			Type string `json:"type"`
			*NameAndWireValue
		}{
			Type:             f.Type,
			NameAndWireValue: f.File,
		}
		return json.Marshal(marshaler)
	case "fileArray":
		var marshaler = struct {
			Type string `json:"type"`
			*NameAndWireValue
		}{
			Type:             f.Type,
			NameAndWireValue: f.FileArray,
		}
		return json.Marshal(marshaler)
	case "bodyProperty":
		var marshaler = struct {
			Type string `json:"type"`
			*NamedParameter
		}{
			Type:           f.Type,
			NamedParameter: f.BodyProperty,
		}
		return json.Marshal(marshaler)
	}
}

type FileUploadRequestBodyPropertyVisitor interface {
	VisitFile(*NameAndWireValue) error
	VisitFileArray(*NameAndWireValue) error
	VisitBodyProperty(*NamedParameter) error
}

func (f *FileUploadRequestBodyProperty) Accept(visitor FileUploadRequestBodyPropertyVisitor) error {
	switch f.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", f.Type, f)
	case "file":
		return visitor.VisitFile(f.File)
	case "fileArray":
		return visitor.VisitFileArray(f.FileArray)
	case "bodyProperty":
		return visitor.VisitBodyProperty(f.BodyProperty)
	}
}

type InlinedRequest struct {
	Declaration     *Declaration            `json:"declaration,omitempty"`
	PathParameters  []*NamedParameter       `json:"pathParameters,omitempty"`
	QueryParameters []*NamedParameter       `json:"queryParameters,omitempty"`
	Headers         []*NamedParameter       `json:"headers,omitempty"`
	Body            *InlinedRequestBody     `json:"body,omitempty"`
	Metadata        *InlinedRequestMetadata `json:"metadata,omitempty"`
}

func (i *InlinedRequest) String() string {
	if value, err := core.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type InlinedRequestBody struct {
	Type       string
	Properties []*NamedParameter
	Referenced *ReferencedRequestBody
	FileUpload *FileUploadRequestBody
}

func NewInlinedRequestBodyFromProperties(value []*NamedParameter) *InlinedRequestBody {
	return &InlinedRequestBody{Type: "properties", Properties: value}
}

func NewInlinedRequestBodyFromReferenced(value *ReferencedRequestBody) *InlinedRequestBody {
	return &InlinedRequestBody{Type: "referenced", Referenced: value}
}

func NewInlinedRequestBodyFromFileUpload(value *FileUploadRequestBody) *InlinedRequestBody {
	return &InlinedRequestBody{Type: "fileUpload", FileUpload: value}
}

func (i *InlinedRequestBody) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	i.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "properties":
		var valueUnmarshaler struct {
			Properties []*NamedParameter `json:"value,omitempty"`
		}
		if err := json.Unmarshal(data, &valueUnmarshaler); err != nil {
			return err
		}
		i.Properties = valueUnmarshaler.Properties
	case "referenced":
		value := new(ReferencedRequestBody)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		i.Referenced = value
	case "fileUpload":
		value := new(FileUploadRequestBody)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		i.FileUpload = value
	}
	return nil
}

func (i InlinedRequestBody) MarshalJSON() ([]byte, error) {
	switch i.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", i.Type, i)
	case "properties":
		var marshaler = struct {
			Type       string            `json:"type"`
			Properties []*NamedParameter `json:"value,omitempty"`
		}{
			Type:       i.Type,
			Properties: i.Properties,
		}
		return json.Marshal(marshaler)
	case "referenced":
		var marshaler = struct {
			Type string `json:"type"`
			*ReferencedRequestBody
		}{
			Type:                  i.Type,
			ReferencedRequestBody: i.Referenced,
		}
		return json.Marshal(marshaler)
	case "fileUpload":
		var marshaler = struct {
			Type string `json:"type"`
			*FileUploadRequestBody
		}{
			Type:                  i.Type,
			FileUploadRequestBody: i.FileUpload,
		}
		return json.Marshal(marshaler)
	}
}

type InlinedRequestBodyVisitor interface {
	VisitProperties([]*NamedParameter) error
	VisitReferenced(*ReferencedRequestBody) error
	VisitFileUpload(*FileUploadRequestBody) error
}

func (i *InlinedRequestBody) Accept(visitor InlinedRequestBodyVisitor) error {
	switch i.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", i.Type, i)
	case "properties":
		return visitor.VisitProperties(i.Properties)
	case "referenced":
		return visitor.VisitReferenced(i.Referenced)
	case "fileUpload":
		return visitor.VisitFileUpload(i.FileUpload)
	}
}

type InlinedRequestMetadata struct {
	// If true, the path parameters should be included as properties in the
	// inlined request type, but only if the generator is explicitly configured
	// to do so.
	//
	// By default, the path parameters are generated as positional parameters.
	IncludePathParameters bool `json:"includePathParameters"`
	// If true, the path parameters are the only parameters specified in the
	// inlined request.
	//
	// In combination with includePathParameters, this influences whether or not the
	// inlined request type should be generated at all.
	OnlyPathParameters bool `json:"onlyPathParameters"`
}

func (i *InlinedRequestMetadata) String() string {
	if value, err := core.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

type ReferencedRequestBody struct {
	BodyKey  *Name                      `json:"bodyKey,omitempty"`
	BodyType *ReferencedRequestBodyType `json:"bodyType,omitempty"`
}

func (r *ReferencedRequestBody) String() string {
	if value, err := core.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type ReferencedRequestBodyType struct {
	Type          string
	Bytes         interface{}
	TypeReference *TypeReference
}

func NewReferencedRequestBodyTypeFromBytes(value interface{}) *ReferencedRequestBodyType {
	return &ReferencedRequestBodyType{Type: "bytes", Bytes: value}
}

func NewReferencedRequestBodyTypeFromTypeReference(value *TypeReference) *ReferencedRequestBodyType {
	return &ReferencedRequestBodyType{Type: "typeReference", TypeReference: value}
}

func (r *ReferencedRequestBodyType) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	r.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "bytes":
		value := make(map[string]interface{})
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		r.Bytes = value
	case "typeReference":
		var valueUnmarshaler struct {
			TypeReference *TypeReference `json:"value,omitempty"`
		}
		if err := json.Unmarshal(data, &valueUnmarshaler); err != nil {
			return err
		}
		r.TypeReference = valueUnmarshaler.TypeReference
	}
	return nil
}

func (r ReferencedRequestBodyType) MarshalJSON() ([]byte, error) {
	switch r.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", r.Type, r)
	case "bytes":
		var marshaler = struct {
			Type  string      `json:"type"`
			Bytes interface{} `json:"bytes,omitempty"`
		}{
			Type:  r.Type,
			Bytes: r.Bytes,
		}
		return json.Marshal(marshaler)
	case "typeReference":
		var marshaler = struct {
			Type          string         `json:"type"`
			TypeReference *TypeReference `json:"value,omitempty"`
		}{
			Type:          r.Type,
			TypeReference: r.TypeReference,
		}
		return json.Marshal(marshaler)
	}
}

type ReferencedRequestBodyTypeVisitor interface {
	VisitBytes(interface{}) error
	VisitTypeReference(*TypeReference) error
}

func (r *ReferencedRequestBodyType) Accept(visitor ReferencedRequestBodyTypeVisitor) error {
	switch r.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", r.Type, r)
	case "bytes":
		return visitor.VisitBytes(r.Bytes)
	case "typeReference":
		return visitor.VisitTypeReference(r.TypeReference)
	}
}

// Represents the request parameters required to call a specific endpoint.
type Request struct {
	Type    string
	Body    *BodyRequest
	Inlined *InlinedRequest
}

func NewRequestFromBody(value *BodyRequest) *Request {
	return &Request{Type: "body", Body: value}
}

func NewRequestFromInlined(value *InlinedRequest) *Request {
	return &Request{Type: "inlined", Inlined: value}
}

func (r *Request) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	r.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "body":
		value := new(BodyRequest)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		r.Body = value
	case "inlined":
		value := new(InlinedRequest)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		r.Inlined = value
	}
	return nil
}

func (r Request) MarshalJSON() ([]byte, error) {
	switch r.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", r.Type, r)
	case "body":
		var marshaler = struct {
			Type string `json:"type"`
			*BodyRequest
		}{
			Type:        r.Type,
			BodyRequest: r.Body,
		}
		return json.Marshal(marshaler)
	case "inlined":
		var marshaler = struct {
			Type string `json:"type"`
			*InlinedRequest
		}{
			Type:           r.Type,
			InlinedRequest: r.Inlined,
		}
		return json.Marshal(marshaler)
	}
}

type RequestVisitor interface {
	VisitBody(*BodyRequest) error
	VisitInlined(*InlinedRequest) error
}

func (r *Request) Accept(visitor RequestVisitor) error {
	switch r.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", r.Type, r)
	case "body":
		return visitor.VisitBody(r.Body)
	case "inlined":
		return visitor.VisitInlined(r.Inlined)
	}
}

// Represents the response returned by a specific endpoint.
//
// For now, we only support json responses, but this is set up to support a
// variety of other endpoint response types (e.g. file download, pagination,
// streaming, etc).
type Response struct {
	Type            string
	Json            interface{}
	Streaming       interface{}
	StreamParameter interface{}
	FileDownload    interface{}
	Text            interface{}
	Bytes           interface{}
}

func NewResponseFromJson(value interface{}) *Response {
	return &Response{Type: "json", Json: value}
}

func NewResponseFromStreaming(value interface{}) *Response {
	return &Response{Type: "streaming", Streaming: value}
}

func NewResponseFromStreamParameter(value interface{}) *Response {
	return &Response{Type: "streamParameter", StreamParameter: value}
}

func NewResponseFromFileDownload(value interface{}) *Response {
	return &Response{Type: "fileDownload", FileDownload: value}
}

func NewResponseFromText(value interface{}) *Response {
	return &Response{Type: "text", Text: value}
}

func NewResponseFromBytes(value interface{}) *Response {
	return &Response{Type: "bytes", Bytes: value}
}

func (r *Response) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	r.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "json":
		value := make(map[string]interface{})
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		r.Json = value
	case "streaming":
		value := make(map[string]interface{})
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		r.Streaming = value
	case "streamParameter":
		value := make(map[string]interface{})
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		r.StreamParameter = value
	case "fileDownload":
		value := make(map[string]interface{})
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		r.FileDownload = value
	case "text":
		value := make(map[string]interface{})
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		r.Text = value
	case "bytes":
		value := make(map[string]interface{})
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		r.Bytes = value
	}
	return nil
}

func (r Response) MarshalJSON() ([]byte, error) {
	switch r.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", r.Type, r)
	case "json":
		var marshaler = struct {
			Type string      `json:"type"`
			Json interface{} `json:"json,omitempty"`
		}{
			Type: r.Type,
			Json: r.Json,
		}
		return json.Marshal(marshaler)
	case "streaming":
		var marshaler = struct {
			Type      string      `json:"type"`
			Streaming interface{} `json:"streaming,omitempty"`
		}{
			Type:      r.Type,
			Streaming: r.Streaming,
		}
		return json.Marshal(marshaler)
	case "streamParameter":
		var marshaler = struct {
			Type            string      `json:"type"`
			StreamParameter interface{} `json:"streamParameter,omitempty"`
		}{
			Type:            r.Type,
			StreamParameter: r.StreamParameter,
		}
		return json.Marshal(marshaler)
	case "fileDownload":
		var marshaler = struct {
			Type         string      `json:"type"`
			FileDownload interface{} `json:"fileDownload,omitempty"`
		}{
			Type:         r.Type,
			FileDownload: r.FileDownload,
		}
		return json.Marshal(marshaler)
	case "text":
		var marshaler = struct {
			Type string      `json:"type"`
			Text interface{} `json:"text,omitempty"`
		}{
			Type: r.Type,
			Text: r.Text,
		}
		return json.Marshal(marshaler)
	case "bytes":
		var marshaler = struct {
			Type  string      `json:"type"`
			Bytes interface{} `json:"bytes,omitempty"`
		}{
			Type:  r.Type,
			Bytes: r.Bytes,
		}
		return json.Marshal(marshaler)
	}
}

type ResponseVisitor interface {
	VisitJson(interface{}) error
	VisitStreaming(interface{}) error
	VisitStreamParameter(interface{}) error
	VisitFileDownload(interface{}) error
	VisitText(interface{}) error
	VisitBytes(interface{}) error
}

func (r *Response) Accept(visitor ResponseVisitor) error {
	switch r.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", r.Type, r)
	case "json":
		return visitor.VisitJson(r.Json)
	case "streaming":
		return visitor.VisitStreaming(r.Streaming)
	case "streamParameter":
		return visitor.VisitStreamParameter(r.StreamParameter)
	case "fileDownload":
		return visitor.VisitFileDownload(r.FileDownload)
	case "text":
		return visitor.VisitText(r.Text)
	case "bytes":
		return visitor.VisitBytes(r.Bytes)
	}
}

type EnvironmentBaseUrlId = string

type EnvironmentBaseUrlWithId struct {
	Id   EnvironmentBaseUrlId `json:"id"`
	Name *Name                `json:"name,omitempty"`
}

func (e *EnvironmentBaseUrlWithId) String() string {
	if value, err := core.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type EnvironmentId = string

type EnvironmentUrl = string

// Represents the value to use for a specific environment. There are three cases:
//
// 1. When sent as an EnvironmentId string, the generator assumes the value matches the name of the
// environment (e.g. "Staging"), and returns an error otherwise.
//
//  2. If the API supports multiple environment URLs, send a map of URLs, e.g.
//     {
//     "ec2": "https://staging.ec2.aws.com",
//     "s3": "https://staging.s3.aws.com"
//     }
type EnvironmentValues struct {
	typeName                     string
	EnvironmentId                EnvironmentId
	MultipleEnvironmentUrlValues MultipleEnvironmentUrlValues
}

func NewEnvironmentValuesFromEnvironmentId(value EnvironmentId) *EnvironmentValues {
	return &EnvironmentValues{typeName: "environmentId", EnvironmentId: value}
}

func NewEnvironmentValuesFromMultipleEnvironmentUrlValues(value MultipleEnvironmentUrlValues) *EnvironmentValues {
	return &EnvironmentValues{typeName: "multipleEnvironmentUrlValues", MultipleEnvironmentUrlValues: value}
}

func (e *EnvironmentValues) UnmarshalJSON(data []byte) error {
	var valueEnvironmentId EnvironmentId
	if err := json.Unmarshal(data, &valueEnvironmentId); err == nil {
		e.typeName = "environmentId"
		e.EnvironmentId = valueEnvironmentId
		return nil
	}
	var valueMultipleEnvironmentUrlValues MultipleEnvironmentUrlValues
	if err := json.Unmarshal(data, &valueMultipleEnvironmentUrlValues); err == nil {
		e.typeName = "multipleEnvironmentUrlValues"
		e.MultipleEnvironmentUrlValues = valueMultipleEnvironmentUrlValues
		return nil
	}
	return fmt.Errorf("%s cannot be deserialized as a %T", data, e)
}

func (e EnvironmentValues) MarshalJSON() ([]byte, error) {
	switch e.typeName {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", e.typeName, e)
	case "environmentId":
		return json.Marshal(e.EnvironmentId)
	case "multipleEnvironmentUrlValues":
		return json.Marshal(e.MultipleEnvironmentUrlValues)
	}
}

type EnvironmentValuesVisitor interface {
	VisitEnvironmentId(EnvironmentId) error
	VisitMultipleEnvironmentUrlValues(MultipleEnvironmentUrlValues) error
}

func (e *EnvironmentValues) Accept(visitor EnvironmentValuesVisitor) error {
	switch e.typeName {
	default:
		return fmt.Errorf("invalid type %s in %T", e.typeName, e)
	case "environmentId":
		return visitor.VisitEnvironmentId(e.EnvironmentId)
	case "multipleEnvironmentUrlValues":
		return visitor.VisitMultipleEnvironmentUrlValues(e.MultipleEnvironmentUrlValues)
	}
}

type Environments struct {
	Type             string
	SingleBaseUrl    *SingleBaseUrlEnvironments
	MultipleBaseUrls *MultipleBaseUrlsEnvironments
}

func NewEnvironmentsFromSingleBaseUrl(value *SingleBaseUrlEnvironments) *Environments {
	return &Environments{Type: "singleBaseUrl", SingleBaseUrl: value}
}

func NewEnvironmentsFromMultipleBaseUrls(value *MultipleBaseUrlsEnvironments) *Environments {
	return &Environments{Type: "multipleBaseUrls", MultipleBaseUrls: value}
}

func (e *Environments) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	e.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "singleBaseUrl":
		value := new(SingleBaseUrlEnvironments)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		e.SingleBaseUrl = value
	case "multipleBaseUrls":
		value := new(MultipleBaseUrlsEnvironments)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		e.MultipleBaseUrls = value
	}
	return nil
}

func (e Environments) MarshalJSON() ([]byte, error) {
	switch e.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", e.Type, e)
	case "singleBaseUrl":
		var marshaler = struct {
			Type string `json:"type"`
			*SingleBaseUrlEnvironments
		}{
			Type:                      e.Type,
			SingleBaseUrlEnvironments: e.SingleBaseUrl,
		}
		return json.Marshal(marshaler)
	case "multipleBaseUrls":
		var marshaler = struct {
			Type string `json:"type"`
			*MultipleBaseUrlsEnvironments
		}{
			Type:                         e.Type,
			MultipleBaseUrlsEnvironments: e.MultipleBaseUrls,
		}
		return json.Marshal(marshaler)
	}
}

type EnvironmentsVisitor interface {
	VisitSingleBaseUrl(*SingleBaseUrlEnvironments) error
	VisitMultipleBaseUrls(*MultipleBaseUrlsEnvironments) error
}

func (e *Environments) Accept(visitor EnvironmentsVisitor) error {
	switch e.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", e.Type, e)
	case "singleBaseUrl":
		return visitor.VisitSingleBaseUrl(e.SingleBaseUrl)
	case "multipleBaseUrls":
		return visitor.VisitMultipleBaseUrls(e.MultipleBaseUrls)
	}
}

type EnvironmentsConfig struct {
	DefaultEnvironment *EnvironmentId `json:"defaultEnvironment,omitempty"`
	Environments       *Environments  `json:"environments,omitempty"`
}

func (e *EnvironmentsConfig) String() string {
	if value, err := core.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type MultipleBaseUrlsEnvironment struct {
	Docs *string                                 `json:"docs,omitempty"`
	Id   EnvironmentId                           `json:"id"`
	Name *Name                                   `json:"name,omitempty"`
	Urls map[EnvironmentBaseUrlId]EnvironmentUrl `json:"urls,omitempty"`
}

func (m *MultipleBaseUrlsEnvironment) String() string {
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MultipleBaseUrlsEnvironments struct {
	BaseUrls     []*EnvironmentBaseUrlWithId    `json:"baseUrls,omitempty"`
	Environments []*MultipleBaseUrlsEnvironment `json:"environments,omitempty"`
}

func (m *MultipleBaseUrlsEnvironments) String() string {
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type MultipleEnvironmentUrlValues = map[EnvironmentBaseUrlId]EnvironmentUrl

type SingleBaseUrlEnvironment struct {
	Docs *string        `json:"docs,omitempty"`
	Id   EnvironmentId  `json:"id"`
	Name *Name          `json:"name,omitempty"`
	Url  EnvironmentUrl `json:"url"`
}

func (s *SingleBaseUrlEnvironment) String() string {
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SingleBaseUrlEnvironments struct {
	Environments []*SingleBaseUrlEnvironment `json:"environments,omitempty"`
}

func (s *SingleBaseUrlEnvironments) String() string {
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type HttpMethod string

const (
	HttpMethodGet    HttpMethod = "GET"
	HttpMethodPost   HttpMethod = "POST"
	HttpMethodPut    HttpMethod = "PUT"
	HttpMethodPatch  HttpMethod = "PATCH"
	HttpMethodDelete HttpMethod = "DELETE"
	HttpMethodHead   HttpMethod = "HEAD"
)

func NewHttpMethodFromString(s string) (HttpMethod, error) {
	switch s {
	case "GET":
		return HttpMethodGet, nil
	case "POST":
		return HttpMethodPost, nil
	case "PUT":
		return HttpMethodPut, nil
	case "PATCH":
		return HttpMethodPatch, nil
	case "DELETE":
		return HttpMethodDelete, nil
	case "HEAD":
		return HttpMethodHead, nil
	}
	var t HttpMethod
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (h HttpMethod) Ptr() *HttpMethod {
	return &h
}

type CratesPublishInfo struct {
	Version     string  `json:"version"`
	PackageName string  `json:"packageName"`
	RepoUrl     *string `json:"repoUrl,omitempty"`
}

func (c *CratesPublishInfo) String() string {
	if value, err := core.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// This represents the IR required to generate dynamic snippets.
//
// This IR minimizes the space required to generate snippets in a variety
// of environments (e.g. web, offline, etc).
type DynamicIntermediateRepresentation struct {
	// The version of the dynamic IR. This is independent from the version
	// of the primary IR.
	Types        map[TypeId]*NamedType    `json:"types,omitempty"`
	Endpoints    map[EndpointId]*Endpoint `json:"endpoints,omitempty"`
	Environments *EnvironmentsConfig      `json:"environments,omitempty"`
	// The headers that are required on every request. These headers
	// are typically included in the SDK's client constructor.
	Headers []*NamedParameter `json:"headers,omitempty"`
	// The path parameters that are required on every request. These
	// path parameters are typically included in the SDK's client
	// constructor.
	PathParameters []*NamedParameter `json:"pathParameters,omitempty"`
	// Variables that are configured at the client level and can be
	// referenced in path parameters and other contexts.
	Variables       []*VariableDeclaration `json:"variables,omitempty"`
	GeneratorConfig *GeneratorConfig       `json:"generatorConfig,omitempty"`
	version         string
}

func (d *DynamicIntermediateRepresentation) Version() string {
	return d.version
}

func (d *DynamicIntermediateRepresentation) UnmarshalJSON(data []byte) error {
	type unmarshaler DynamicIntermediateRepresentation
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*d = DynamicIntermediateRepresentation(value)
	d.version = "1.0.0"
	return nil
}

func (d *DynamicIntermediateRepresentation) MarshalJSON() ([]byte, error) {
	type embed DynamicIntermediateRepresentation
	var marshaler = struct {
		embed
		Version string `json:"version"`
	}{
		embed:   embed(*d),
		Version: "1.0.0",
	}
	return json.Marshal(marshaler)
}

func (d *DynamicIntermediateRepresentation) String() string {
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

// The configuration for the generator. This is a simplified version of the
// generator-exec GeneratorConfig configuration.
type GeneratorConfig struct {
	// The name of the API. This is equivalent to the workspace name in the
	// generator-exec configuration.
	ApiName      string                 `json:"apiName"`
	Organization string                 `json:"organization"`
	CustomConfig interface{}            `json:"customConfig,omitempty"`
	OutputConfig *GeneratorOutputConfig `json:"outputConfig,omitempty"`
}

func (g *GeneratorConfig) String() string {
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// The configuration for the output of the generator. This is a simplified version of
// the generator-exec output.mode configuration.
type GeneratorOutputConfig struct {
	Type    string
	Publish *PublishInfo
	Local   interface{}
}

func NewGeneratorOutputConfigFromPublish(value *PublishInfo) *GeneratorOutputConfig {
	return &GeneratorOutputConfig{Type: "publish", Publish: value}
}

func NewGeneratorOutputConfigFromLocal(value interface{}) *GeneratorOutputConfig {
	return &GeneratorOutputConfig{Type: "local", Local: value}
}

func (g *GeneratorOutputConfig) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	g.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "publish":
		var valueUnmarshaler struct {
			Publish *PublishInfo `json:"value,omitempty"`
		}
		if err := json.Unmarshal(data, &valueUnmarshaler); err != nil {
			return err
		}
		g.Publish = valueUnmarshaler.Publish
	case "local":
		value := make(map[string]interface{})
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		g.Local = value
	}
	return nil
}

func (g GeneratorOutputConfig) MarshalJSON() ([]byte, error) {
	switch g.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", g.Type, g)
	case "publish":
		var marshaler = struct {
			Type    string       `json:"type"`
			Publish *PublishInfo `json:"value,omitempty"`
		}{
			Type:    g.Type,
			Publish: g.Publish,
		}
		return json.Marshal(marshaler)
	case "local":
		var marshaler = struct {
			Type  string      `json:"type"`
			Local interface{} `json:"local,omitempty"`
		}{
			Type:  g.Type,
			Local: g.Local,
		}
		return json.Marshal(marshaler)
	}
}

type GeneratorOutputConfigVisitor interface {
	VisitPublish(*PublishInfo) error
	VisitLocal(interface{}) error
}

func (g *GeneratorOutputConfig) Accept(visitor GeneratorOutputConfigVisitor) error {
	switch g.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", g.Type, g)
	case "publish":
		return visitor.VisitPublish(g.Publish)
	case "local":
		return visitor.VisitLocal(g.Local)
	}
}

type GoPublishInfo struct {
	Version string `json:"version"`
	// A full repo url (i.e. https://github.com/fern-api/fern)
	RepoUrl string `json:"repoUrl"`
}

func (g *GoPublishInfo) String() string {
	if value, err := core.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

type MavenPublishInfo struct {
	Version    string  `json:"version"`
	Coordinate string  `json:"coordinate"`
	RepoUrl    *string `json:"repoUrl,omitempty"`
}

func (m *MavenPublishInfo) String() string {
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type NpmPublishInfo struct {
	Version     string  `json:"version"`
	PackageName string  `json:"packageName"`
	RepoUrl     *string `json:"repoUrl,omitempty"`
}

func (n *NpmPublishInfo) String() string {
	if value, err := core.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

type NugetPublishInfo struct {
	Version     string  `json:"version"`
	PackageName string  `json:"packageName"`
	RepoUrl     *string `json:"repoUrl,omitempty"`
}

func (n *NugetPublishInfo) String() string {
	if value, err := core.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

type PublishInfo struct {
	Type     string
	Go       *GoPublishInfo
	Swift    *SwiftPublishInfo
	Maven    *MavenPublishInfo
	Npm      *NpmPublishInfo
	Nuget    *NugetPublishInfo
	Pypi     *PypiPublishInfo
	Rubygems *RubyGemsPublishInfo
	Crates   *CratesPublishInfo
}

func NewPublishInfoFromGo(value *GoPublishInfo) *PublishInfo {
	return &PublishInfo{Type: "go", Go: value}
}

func NewPublishInfoFromSwift(value *SwiftPublishInfo) *PublishInfo {
	return &PublishInfo{Type: "swift", Swift: value}
}

func NewPublishInfoFromMaven(value *MavenPublishInfo) *PublishInfo {
	return &PublishInfo{Type: "maven", Maven: value}
}

func NewPublishInfoFromNpm(value *NpmPublishInfo) *PublishInfo {
	return &PublishInfo{Type: "npm", Npm: value}
}

func NewPublishInfoFromNuget(value *NugetPublishInfo) *PublishInfo {
	return &PublishInfo{Type: "nuget", Nuget: value}
}

func NewPublishInfoFromPypi(value *PypiPublishInfo) *PublishInfo {
	return &PublishInfo{Type: "pypi", Pypi: value}
}

func NewPublishInfoFromRubygems(value *RubyGemsPublishInfo) *PublishInfo {
	return &PublishInfo{Type: "rubygems", Rubygems: value}
}

func NewPublishInfoFromCrates(value *CratesPublishInfo) *PublishInfo {
	return &PublishInfo{Type: "crates", Crates: value}
}

func (p *PublishInfo) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	p.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "go":
		value := new(GoPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Go = value
	case "swift":
		value := new(SwiftPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Swift = value
	case "maven":
		value := new(MavenPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Maven = value
	case "npm":
		value := new(NpmPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Npm = value
	case "nuget":
		value := new(NugetPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Nuget = value
	case "pypi":
		value := new(PypiPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Pypi = value
	case "rubygems":
		value := new(RubyGemsPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Rubygems = value
	case "crates":
		value := new(CratesPublishInfo)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		p.Crates = value
	}
	return nil
}

func (p PublishInfo) MarshalJSON() ([]byte, error) {
	switch p.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", p.Type, p)
	case "go":
		var marshaler = struct {
			Type string `json:"type"`
			*GoPublishInfo
		}{
			Type:          p.Type,
			GoPublishInfo: p.Go,
		}
		return json.Marshal(marshaler)
	case "swift":
		var marshaler = struct {
			Type string `json:"type"`
			*SwiftPublishInfo
		}{
			Type:             p.Type,
			SwiftPublishInfo: p.Swift,
		}
		return json.Marshal(marshaler)
	case "maven":
		var marshaler = struct {
			Type string `json:"type"`
			*MavenPublishInfo
		}{
			Type:             p.Type,
			MavenPublishInfo: p.Maven,
		}
		return json.Marshal(marshaler)
	case "npm":
		var marshaler = struct {
			Type string `json:"type"`
			*NpmPublishInfo
		}{
			Type:           p.Type,
			NpmPublishInfo: p.Npm,
		}
		return json.Marshal(marshaler)
	case "nuget":
		var marshaler = struct {
			Type string `json:"type"`
			*NugetPublishInfo
		}{
			Type:             p.Type,
			NugetPublishInfo: p.Nuget,
		}
		return json.Marshal(marshaler)
	case "pypi":
		var marshaler = struct {
			Type string `json:"type"`
			*PypiPublishInfo
		}{
			Type:            p.Type,
			PypiPublishInfo: p.Pypi,
		}
		return json.Marshal(marshaler)
	case "rubygems":
		var marshaler = struct {
			Type string `json:"type"`
			*RubyGemsPublishInfo
		}{
			Type:                p.Type,
			RubyGemsPublishInfo: p.Rubygems,
		}
		return json.Marshal(marshaler)
	case "crates":
		var marshaler = struct {
			Type string `json:"type"`
			*CratesPublishInfo
		}{
			Type:              p.Type,
			CratesPublishInfo: p.Crates,
		}
		return json.Marshal(marshaler)
	}
}

type PublishInfoVisitor interface {
	VisitGo(*GoPublishInfo) error
	VisitSwift(*SwiftPublishInfo) error
	VisitMaven(*MavenPublishInfo) error
	VisitNpm(*NpmPublishInfo) error
	VisitNuget(*NugetPublishInfo) error
	VisitPypi(*PypiPublishInfo) error
	VisitRubygems(*RubyGemsPublishInfo) error
	VisitCrates(*CratesPublishInfo) error
}

func (p *PublishInfo) Accept(visitor PublishInfoVisitor) error {
	switch p.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", p.Type, p)
	case "go":
		return visitor.VisitGo(p.Go)
	case "swift":
		return visitor.VisitSwift(p.Swift)
	case "maven":
		return visitor.VisitMaven(p.Maven)
	case "npm":
		return visitor.VisitNpm(p.Npm)
	case "nuget":
		return visitor.VisitNuget(p.Nuget)
	case "pypi":
		return visitor.VisitPypi(p.Pypi)
	case "rubygems":
		return visitor.VisitRubygems(p.Rubygems)
	case "crates":
		return visitor.VisitCrates(p.Crates)
	}
}

type PypiPublishInfo struct {
	Version     string  `json:"version"`
	PackageName string  `json:"packageName"`
	RepoUrl     *string `json:"repoUrl,omitempty"`
}

func (p *PypiPublishInfo) String() string {
	if value, err := core.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

type RubyGemsPublishInfo struct {
	Version     string  `json:"version"`
	PackageName string  `json:"packageName"`
	RepoUrl     *string `json:"repoUrl,omitempty"`
}

func (r *RubyGemsPublishInfo) String() string {
	if value, err := core.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}

type SwiftPublishInfo struct {
	Version string `json:"version"`
	// A full repo url (i.e. https://github.com/fern-api/fern)
	RepoUrl string `json:"repoUrl"`
}

func (s *SwiftPublishInfo) String() string {
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

// The user-facing request type used to generate a dynamic snippet.
type EndpointSnippetRequest struct {
	Endpoint        *EndpointLocation  `json:"endpoint,omitempty"`
	BaseUrl         *string            `json:"baseURL,omitempty"`
	Environment     *EnvironmentValues `json:"environment,omitempty"`
	Auth            *AuthValues        `json:"auth,omitempty"`
	PathParameters  *Values            `json:"pathParameters,omitempty"`
	QueryParameters *Values            `json:"queryParameters,omitempty"`
	Headers         *Values            `json:"headers,omitempty"`
	RequestBody     interface{}        `json:"requestBody,omitempty"`
}

func (e *EndpointSnippetRequest) String() string {
	if value, err := core.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

// Snippet values are represented as arbitrary key, value
// pairs (i.e. JSON objects). The keys are expected to be
// in the parameter's wire representation. For path parameters,
// the name will match the parameter name.
type Values = map[string]interface{}

type AliasType struct {
	Declaration   *Declaration   `json:"declaration,omitempty"`
	TypeReference *TypeReference `json:"typeReference,omitempty"`
}

func (a *AliasType) String() string {
	if value, err := core.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

type DiscriminatedUnionType struct {
	Declaration  *Declaration      `json:"declaration,omitempty"`
	Discriminant *NameAndWireValue `json:"discriminant,omitempty"`
	// Map from the discriminant value (e.g. "user") to the type (e.g. User).
	Types map[string]*SingleDiscriminatedUnionType `json:"types,omitempty"`
}

func (d *DiscriminatedUnionType) String() string {
	if value, err := core.StringifyJSON(d); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", d)
}

type EnumType struct {
	Declaration *Declaration        `json:"declaration,omitempty"`
	Values      []*NameAndWireValue `json:"values,omitempty"`
}

func (e *EnumType) String() string {
	if value, err := core.StringifyJSON(e); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", e)
}

type LiteralType struct {
	Type    string
	Boolean bool
	String  string
}

func NewLiteralTypeFromBoolean(value bool) *LiteralType {
	return &LiteralType{Type: "boolean", Boolean: value}
}

func NewLiteralTypeFromString(value string) *LiteralType {
	return &LiteralType{Type: "string", String: value}
}

func (l *LiteralType) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	l.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "boolean":
		var valueUnmarshaler struct {
			Boolean bool `json:"value"`
		}
		if err := json.Unmarshal(data, &valueUnmarshaler); err != nil {
			return err
		}
		l.Boolean = valueUnmarshaler.Boolean
	case "string":
		var valueUnmarshaler struct {
			String string `json:"value"`
		}
		if err := json.Unmarshal(data, &valueUnmarshaler); err != nil {
			return err
		}
		l.String = valueUnmarshaler.String
	}
	return nil
}

func (l LiteralType) MarshalJSON() ([]byte, error) {
	switch l.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", l.Type, l)
	case "boolean":
		var marshaler = struct {
			Type    string `json:"type"`
			Boolean bool   `json:"value"`
		}{
			Type:    l.Type,
			Boolean: l.Boolean,
		}
		return json.Marshal(marshaler)
	case "string":
		var marshaler = struct {
			Type   string `json:"type"`
			String string `json:"value"`
		}{
			Type:   l.Type,
			String: l.String,
		}
		return json.Marshal(marshaler)
	}
}

type LiteralTypeVisitor interface {
	VisitBoolean(bool) error
	VisitString(string) error
}

func (l *LiteralType) Accept(visitor LiteralTypeVisitor) error {
	switch l.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", l.Type, l)
	case "boolean":
		return visitor.VisitBoolean(l.Boolean)
	case "string":
		return visitor.VisitString(l.String)
	}
}

type MapType struct {
	Key   *TypeReference `json:"key,omitempty"`
	Value *TypeReference `json:"value,omitempty"`
}

func (m *MapType) String() string {
	if value, err := core.StringifyJSON(m); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", m)
}

type NamedParameter struct {
	Name           *NameAndWireValue     `json:"name,omitempty"`
	TypeReference  *TypeReference        `json:"typeReference,omitempty"`
	PropertyAccess *ObjectPropertyAccess `json:"propertyAccess,omitempty"`
	// If set, this parameter references a variable defined at the client level
	Variable *string `json:"variable,omitempty"`
}

func (n *NamedParameter) String() string {
	if value, err := core.StringifyJSON(n); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", n)
}

// Represents the type of a parameter that can be used to generate a dynamic type.
type NamedType struct {
	Type                 string
	Alias                *AliasType
	Enum                 *EnumType
	Object               *ObjectType
	DiscriminatedUnion   *DiscriminatedUnionType
	UndiscriminatedUnion *UndiscriminatedUnionType
}

func NewNamedTypeFromAlias(value *AliasType) *NamedType {
	return &NamedType{Type: "alias", Alias: value}
}

func NewNamedTypeFromEnum(value *EnumType) *NamedType {
	return &NamedType{Type: "enum", Enum: value}
}

func NewNamedTypeFromObject(value *ObjectType) *NamedType {
	return &NamedType{Type: "object", Object: value}
}

func NewNamedTypeFromDiscriminatedUnion(value *DiscriminatedUnionType) *NamedType {
	return &NamedType{Type: "discriminatedUnion", DiscriminatedUnion: value}
}

func NewNamedTypeFromUndiscriminatedUnion(value *UndiscriminatedUnionType) *NamedType {
	return &NamedType{Type: "undiscriminatedUnion", UndiscriminatedUnion: value}
}

func (n *NamedType) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	n.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "alias":
		value := new(AliasType)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.Alias = value
	case "enum":
		value := new(EnumType)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.Enum = value
	case "object":
		value := new(ObjectType)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.Object = value
	case "discriminatedUnion":
		value := new(DiscriminatedUnionType)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.DiscriminatedUnion = value
	case "undiscriminatedUnion":
		value := new(UndiscriminatedUnionType)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		n.UndiscriminatedUnion = value
	}
	return nil
}

func (n NamedType) MarshalJSON() ([]byte, error) {
	switch n.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", n.Type, n)
	case "alias":
		var marshaler = struct {
			Type string `json:"type"`
			*AliasType
		}{
			Type:      n.Type,
			AliasType: n.Alias,
		}
		return json.Marshal(marshaler)
	case "enum":
		var marshaler = struct {
			Type string `json:"type"`
			*EnumType
		}{
			Type:     n.Type,
			EnumType: n.Enum,
		}
		return json.Marshal(marshaler)
	case "object":
		var marshaler = struct {
			Type string `json:"type"`
			*ObjectType
		}{
			Type:       n.Type,
			ObjectType: n.Object,
		}
		return json.Marshal(marshaler)
	case "discriminatedUnion":
		var marshaler = struct {
			Type string `json:"type"`
			*DiscriminatedUnionType
		}{
			Type:                   n.Type,
			DiscriminatedUnionType: n.DiscriminatedUnion,
		}
		return json.Marshal(marshaler)
	case "undiscriminatedUnion":
		var marshaler = struct {
			Type string `json:"type"`
			*UndiscriminatedUnionType
		}{
			Type:                     n.Type,
			UndiscriminatedUnionType: n.UndiscriminatedUnion,
		}
		return json.Marshal(marshaler)
	}
}

type NamedTypeVisitor interface {
	VisitAlias(*AliasType) error
	VisitEnum(*EnumType) error
	VisitObject(*ObjectType) error
	VisitDiscriminatedUnion(*DiscriminatedUnionType) error
	VisitUndiscriminatedUnion(*UndiscriminatedUnionType) error
}

func (n *NamedType) Accept(visitor NamedTypeVisitor) error {
	switch n.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", n.Type, n)
	case "alias":
		return visitor.VisitAlias(n.Alias)
	case "enum":
		return visitor.VisitEnum(n.Enum)
	case "object":
		return visitor.VisitObject(n.Object)
	case "discriminatedUnion":
		return visitor.VisitDiscriminatedUnion(n.DiscriminatedUnion)
	case "undiscriminatedUnion":
		return visitor.VisitUndiscriminatedUnion(n.UndiscriminatedUnion)
	}
}

type ObjectPropertyAccess string

const (
	ObjectPropertyAccessReadOnly  ObjectPropertyAccess = "READ_ONLY"
	ObjectPropertyAccessWriteOnly ObjectPropertyAccess = "WRITE_ONLY"
)

func NewObjectPropertyAccessFromString(s string) (ObjectPropertyAccess, error) {
	switch s {
	case "READ_ONLY":
		return ObjectPropertyAccessReadOnly, nil
	case "WRITE_ONLY":
		return ObjectPropertyAccessWriteOnly, nil
	}
	var t ObjectPropertyAccess
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (o ObjectPropertyAccess) Ptr() *ObjectPropertyAccess {
	return &o
}

type ObjectType struct {
	Declaration *Declaration      `json:"declaration,omitempty"`
	Properties  []*NamedParameter `json:"properties,omitempty"`
	// Whether the type allows additional properties.
	AdditionalProperties *bool `json:"additionalProperties,omitempty"`
}

func (o *ObjectType) String() string {
	if value, err := core.StringifyJSON(o); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", o)
}

type PrimitiveTypeV1 string

const (
	PrimitiveTypeV1Integer PrimitiveTypeV1 = "INTEGER"
	// Within the range -2^53 to 2^53
	PrimitiveTypeV1Long       PrimitiveTypeV1 = "LONG"
	PrimitiveTypeV1Uint       PrimitiveTypeV1 = "UINT"
	PrimitiveTypeV1Uint64     PrimitiveTypeV1 = "UINT_64"
	PrimitiveTypeV1Float      PrimitiveTypeV1 = "FLOAT"
	PrimitiveTypeV1Double     PrimitiveTypeV1 = "DOUBLE"
	PrimitiveTypeV1Boolean    PrimitiveTypeV1 = "BOOLEAN"
	PrimitiveTypeV1String     PrimitiveTypeV1 = "STRING"
	PrimitiveTypeV1Date       PrimitiveTypeV1 = "DATE"
	PrimitiveTypeV1DateTime   PrimitiveTypeV1 = "DATE_TIME"
	PrimitiveTypeV1Uuid       PrimitiveTypeV1 = "UUID"
	PrimitiveTypeV1Base64     PrimitiveTypeV1 = "BASE_64"
	PrimitiveTypeV1BigInteger PrimitiveTypeV1 = "BIG_INTEGER"
)

func NewPrimitiveTypeV1FromString(s string) (PrimitiveTypeV1, error) {
	switch s {
	case "INTEGER":
		return PrimitiveTypeV1Integer, nil
	case "LONG":
		return PrimitiveTypeV1Long, nil
	case "UINT":
		return PrimitiveTypeV1Uint, nil
	case "UINT_64":
		return PrimitiveTypeV1Uint64, nil
	case "FLOAT":
		return PrimitiveTypeV1Float, nil
	case "DOUBLE":
		return PrimitiveTypeV1Double, nil
	case "BOOLEAN":
		return PrimitiveTypeV1Boolean, nil
	case "STRING":
		return PrimitiveTypeV1String, nil
	case "DATE":
		return PrimitiveTypeV1Date, nil
	case "DATE_TIME":
		return PrimitiveTypeV1DateTime, nil
	case "UUID":
		return PrimitiveTypeV1Uuid, nil
	case "BASE_64":
		return PrimitiveTypeV1Base64, nil
	case "BIG_INTEGER":
		return PrimitiveTypeV1BigInteger, nil
	}
	var t PrimitiveTypeV1
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (p PrimitiveTypeV1) Ptr() *PrimitiveTypeV1 {
	return &p
}

type SingleDiscriminatedUnionType struct {
	Type                   string
	SamePropertiesAsObject *SingleDiscriminatedUnionTypeObject
	SingleProperty         *SingleDiscriminatedUnionTypeSingleProperty
	NoProperties           *SingleDiscriminatedUnionTypeNoProperties
}

func NewSingleDiscriminatedUnionTypeFromSamePropertiesAsObject(value *SingleDiscriminatedUnionTypeObject) *SingleDiscriminatedUnionType {
	return &SingleDiscriminatedUnionType{Type: "samePropertiesAsObject", SamePropertiesAsObject: value}
}

func NewSingleDiscriminatedUnionTypeFromSingleProperty(value *SingleDiscriminatedUnionTypeSingleProperty) *SingleDiscriminatedUnionType {
	return &SingleDiscriminatedUnionType{Type: "singleProperty", SingleProperty: value}
}

func NewSingleDiscriminatedUnionTypeFromNoProperties(value *SingleDiscriminatedUnionTypeNoProperties) *SingleDiscriminatedUnionType {
	return &SingleDiscriminatedUnionType{Type: "noProperties", NoProperties: value}
}

func (s *SingleDiscriminatedUnionType) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	s.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "samePropertiesAsObject":
		value := new(SingleDiscriminatedUnionTypeObject)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		s.SamePropertiesAsObject = value
	case "singleProperty":
		value := new(SingleDiscriminatedUnionTypeSingleProperty)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		s.SingleProperty = value
	case "noProperties":
		value := new(SingleDiscriminatedUnionTypeNoProperties)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		s.NoProperties = value
	}
	return nil
}

func (s SingleDiscriminatedUnionType) MarshalJSON() ([]byte, error) {
	switch s.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", s.Type, s)
	case "samePropertiesAsObject":
		var marshaler = struct {
			Type string `json:"type"`
			*SingleDiscriminatedUnionTypeObject
		}{
			Type:                               s.Type,
			SingleDiscriminatedUnionTypeObject: s.SamePropertiesAsObject,
		}
		return json.Marshal(marshaler)
	case "singleProperty":
		var marshaler = struct {
			Type string `json:"type"`
			*SingleDiscriminatedUnionTypeSingleProperty
		}{
			Type: s.Type,
			SingleDiscriminatedUnionTypeSingleProperty: s.SingleProperty,
		}
		return json.Marshal(marshaler)
	case "noProperties":
		var marshaler = struct {
			Type string `json:"type"`
			*SingleDiscriminatedUnionTypeNoProperties
		}{
			Type:                                     s.Type,
			SingleDiscriminatedUnionTypeNoProperties: s.NoProperties,
		}
		return json.Marshal(marshaler)
	}
}

type SingleDiscriminatedUnionTypeVisitor interface {
	VisitSamePropertiesAsObject(*SingleDiscriminatedUnionTypeObject) error
	VisitSingleProperty(*SingleDiscriminatedUnionTypeSingleProperty) error
	VisitNoProperties(*SingleDiscriminatedUnionTypeNoProperties) error
}

func (s *SingleDiscriminatedUnionType) Accept(visitor SingleDiscriminatedUnionTypeVisitor) error {
	switch s.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", s.Type, s)
	case "samePropertiesAsObject":
		return visitor.VisitSamePropertiesAsObject(s.SamePropertiesAsObject)
	case "singleProperty":
		return visitor.VisitSingleProperty(s.SingleProperty)
	case "noProperties":
		return visitor.VisitNoProperties(s.NoProperties)
	}
}

type SingleDiscriminatedUnionTypeNoProperties struct {
	DiscriminantValue *NameAndWireValue `json:"discriminantValue,omitempty"`
	// Any properties included here are the base and/or extended properties from the union.
	Properties []*NamedParameter `json:"properties,omitempty"`
}

func (s *SingleDiscriminatedUnionTypeNoProperties) String() string {
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SingleDiscriminatedUnionTypeObject struct {
	TypeId            TypeId            `json:"typeId"`
	DiscriminantValue *NameAndWireValue `json:"discriminantValue,omitempty"`
	// Any properties included here are the base and/or extended properties from the union.
	Properties []*NamedParameter `json:"properties,omitempty"`
}

func (s *SingleDiscriminatedUnionTypeObject) String() string {
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type SingleDiscriminatedUnionTypeSingleProperty struct {
	TypeReference     *TypeReference    `json:"typeReference,omitempty"`
	DiscriminantValue *NameAndWireValue `json:"discriminantValue,omitempty"`
	// Any properties included here are the base and/or extended properties from the union.
	Properties []*NamedParameter `json:"properties,omitempty"`
}

func (s *SingleDiscriminatedUnionTypeSingleProperty) String() string {
	if value, err := core.StringifyJSON(s); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", s)
}

type TypeReference struct {
	Type      string
	List      *TypeReference
	Literal   *LiteralType
	Map       *MapType
	Named     TypeId
	Nullable  *TypeReference
	Optional  *TypeReference
	Primitive PrimitiveTypeV1
	Set       *TypeReference
	Unknown   interface{}
}

func NewTypeReferenceFromList(value *TypeReference) *TypeReference {
	return &TypeReference{Type: "list", List: value}
}

func NewTypeReferenceFromLiteral(value *LiteralType) *TypeReference {
	return &TypeReference{Type: "literal", Literal: value}
}

func NewTypeReferenceFromMap(value *MapType) *TypeReference {
	return &TypeReference{Type: "map", Map: value}
}

func NewTypeReferenceFromNamed(value TypeId) *TypeReference {
	return &TypeReference{Type: "named", Named: value}
}

func NewTypeReferenceFromNullable(value *TypeReference) *TypeReference {
	return &TypeReference{Type: "nullable", Nullable: value}
}

func NewTypeReferenceFromOptional(value *TypeReference) *TypeReference {
	return &TypeReference{Type: "optional", Optional: value}
}

func NewTypeReferenceFromPrimitive(value PrimitiveTypeV1) *TypeReference {
	return &TypeReference{Type: "primitive", Primitive: value}
}

func NewTypeReferenceFromSet(value *TypeReference) *TypeReference {
	return &TypeReference{Type: "set", Set: value}
}

func NewTypeReferenceFromUnknown(value interface{}) *TypeReference {
	return &TypeReference{Type: "unknown", Unknown: value}
}

func (t *TypeReference) UnmarshalJSON(data []byte) error {
	var unmarshaler struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	t.Type = unmarshaler.Type
	switch unmarshaler.Type {
	case "list":
		var valueUnmarshaler struct {
			List *TypeReference `json:"value,omitempty"`
		}
		if err := json.Unmarshal(data, &valueUnmarshaler); err != nil {
			return err
		}
		t.List = valueUnmarshaler.List
	case "literal":
		var valueUnmarshaler struct {
			Literal *LiteralType `json:"value,omitempty"`
		}
		if err := json.Unmarshal(data, &valueUnmarshaler); err != nil {
			return err
		}
		t.Literal = valueUnmarshaler.Literal
	case "map":
		value := new(MapType)
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Map = value
	case "named":
		var valueUnmarshaler struct {
			Named TypeId `json:"value"`
		}
		if err := json.Unmarshal(data, &valueUnmarshaler); err != nil {
			return err
		}
		t.Named = valueUnmarshaler.Named
	case "nullable":
		var valueUnmarshaler struct {
			Nullable *TypeReference `json:"value,omitempty"`
		}
		if err := json.Unmarshal(data, &valueUnmarshaler); err != nil {
			return err
		}
		t.Nullable = valueUnmarshaler.Nullable
	case "optional":
		var valueUnmarshaler struct {
			Optional *TypeReference `json:"value,omitempty"`
		}
		if err := json.Unmarshal(data, &valueUnmarshaler); err != nil {
			return err
		}
		t.Optional = valueUnmarshaler.Optional
	case "primitive":
		var valueUnmarshaler struct {
			Primitive PrimitiveTypeV1 `json:"value,omitempty"`
		}
		if err := json.Unmarshal(data, &valueUnmarshaler); err != nil {
			return err
		}
		t.Primitive = valueUnmarshaler.Primitive
	case "set":
		var valueUnmarshaler struct {
			Set *TypeReference `json:"value,omitempty"`
		}
		if err := json.Unmarshal(data, &valueUnmarshaler); err != nil {
			return err
		}
		t.Set = valueUnmarshaler.Set
	case "unknown":
		value := make(map[string]interface{})
		if err := json.Unmarshal(data, &value); err != nil {
			return err
		}
		t.Unknown = value
	}
	return nil
}

func (t TypeReference) MarshalJSON() ([]byte, error) {
	switch t.Type {
	default:
		return nil, fmt.Errorf("invalid type %s in %T", t.Type, t)
	case "list":
		var marshaler = struct {
			Type string         `json:"type"`
			List *TypeReference `json:"value,omitempty"`
		}{
			Type: t.Type,
			List: t.List,
		}
		return json.Marshal(marshaler)
	case "literal":
		var marshaler = struct {
			Type    string       `json:"type"`
			Literal *LiteralType `json:"value,omitempty"`
		}{
			Type:    t.Type,
			Literal: t.Literal,
		}
		return json.Marshal(marshaler)
	case "map":
		var marshaler = struct {
			Type string `json:"type"`
			*MapType
		}{
			Type:    t.Type,
			MapType: t.Map,
		}
		return json.Marshal(marshaler)
	case "named":
		var marshaler = struct {
			Type  string `json:"type"`
			Named TypeId `json:"value"`
		}{
			Type:  t.Type,
			Named: t.Named,
		}
		return json.Marshal(marshaler)
	case "nullable":
		var marshaler = struct {
			Type     string         `json:"type"`
			Nullable *TypeReference `json:"value,omitempty"`
		}{
			Type:     t.Type,
			Nullable: t.Nullable,
		}
		return json.Marshal(marshaler)
	case "optional":
		var marshaler = struct {
			Type     string         `json:"type"`
			Optional *TypeReference `json:"value,omitempty"`
		}{
			Type:     t.Type,
			Optional: t.Optional,
		}
		return json.Marshal(marshaler)
	case "primitive":
		var marshaler = struct {
			Type      string          `json:"type"`
			Primitive PrimitiveTypeV1 `json:"value,omitempty"`
		}{
			Type:      t.Type,
			Primitive: t.Primitive,
		}
		return json.Marshal(marshaler)
	case "set":
		var marshaler = struct {
			Type string         `json:"type"`
			Set  *TypeReference `json:"value,omitempty"`
		}{
			Type: t.Type,
			Set:  t.Set,
		}
		return json.Marshal(marshaler)
	case "unknown":
		var marshaler = struct {
			Type    string      `json:"type"`
			Unknown interface{} `json:"unknown,omitempty"`
		}{
			Type:    t.Type,
			Unknown: t.Unknown,
		}
		return json.Marshal(marshaler)
	}
}

type TypeReferenceVisitor interface {
	VisitList(*TypeReference) error
	VisitLiteral(*LiteralType) error
	VisitMap(*MapType) error
	VisitNamed(TypeId) error
	VisitNullable(*TypeReference) error
	VisitOptional(*TypeReference) error
	VisitPrimitive(PrimitiveTypeV1) error
	VisitSet(*TypeReference) error
	VisitUnknown(interface{}) error
}

func (t *TypeReference) Accept(visitor TypeReferenceVisitor) error {
	switch t.Type {
	default:
		return fmt.Errorf("invalid type %s in %T", t.Type, t)
	case "list":
		return visitor.VisitList(t.List)
	case "literal":
		return visitor.VisitLiteral(t.Literal)
	case "map":
		return visitor.VisitMap(t.Map)
	case "named":
		return visitor.VisitNamed(t.Named)
	case "nullable":
		return visitor.VisitNullable(t.Nullable)
	case "optional":
		return visitor.VisitOptional(t.Optional)
	case "primitive":
		return visitor.VisitPrimitive(t.Primitive)
	case "set":
		return visitor.VisitSet(t.Set)
	case "unknown":
		return visitor.VisitUnknown(t.Unknown)
	}
}

type UndiscriminatedUnionType struct {
	Declaration *Declaration `json:"declaration,omitempty"`
	// The dynamic type will be rendered with the first type that matches.
	Types []*TypeReference `json:"types,omitempty"`
}

func (u *UndiscriminatedUnionType) String() string {
	if value, err := core.StringifyJSON(u); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", u)
}

// A variable that is configured at the client level and can be
// referenced in path parameters and other contexts.
type VariableDeclaration struct {
	// The unique identifier for the variable
	Id string `json:"id"`
	// The name of the variable
	Name *common.Name `json:"name,omitempty"`
	// The type of the variable
	TypeReference *TypeReference `json:"typeReference,omitempty"`
}

func (v *VariableDeclaration) String() string {
	if value, err := core.StringifyJSON(v); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", v)
}
